### ISSUE TITLE
Update Materia high scores export to match expected columns for Canvas upload

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1071]
The columns produced by the "High Scores" export option do not match what Canvas expects if we choose to upload the CSV to the gradebook. We need to update the columns to the expected values, based on this document: https://community.canvaslms.com/docs/DOC-12786

- Student Name
- Student ID
- SIS User ID (only required if you use SIS)
- SIS Login ID (only required if you use SIS)
- Section
- Assignment (this can be for an existing assignment or a new assignment; retain IDs for existing assignments)

**Comment by iturgeon** [comment]
Looks taken care of to me:

https://github.com/ucfopen/Materia/blob/5c1c65bc585c21fdd166171b7310ec3a8b544d40/fuel/app/classes/materia/session/playdataexporter.php#L167-L207
