### ISSUE TITLE
Updating materia-client-assets locally kinda sucks

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1074]
To get any javascript or CSS updates to appear on your local Docker copy of Materia, the process is messy. It's approximately the following:

1. `rm -rf` the `materia-client-assets` directory from `materia-docker/app/node_modules`
2. `cp -r` your local `materia-client-assets` directory (which has local, un-committed changes you want to test) into `materia-docker/app/node_modules`
3. Run `webpack -p` in `materia-docker/app`

It'd be nice to have a script or process running to watch changes to `materia-client-assets` and update the files in use by Docker Materia automatically.

**Comment by iturgeon** [comment]
There are some scripts there now, closing.

https://github.com/ucfopen/Materia/blob/master/package.json#L10-L20
