### ISSUE TITLE
Materia.ScoreCore update callback should include qsetVersion

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia#1149]
https://github.com/ucfopen/Materia-Server-Client-Assets/blob/master/src/js/materia/materia.scorecore.js#L20

The callback for `update` sends an updated qset and scoreTable, but doesn't pass the new qset's version so any code relying on parsing different qset versions aren't usable.

**Comment by tuanvpham** [comment]
I created a [pull request](https://github.com/ucfopen/Materia-Server-Client-Assets/pull/39) on Materia Server Client Assets repo for this issue.

**Comment by clpetersonucf** [comment]
Added via https://github.com/ucfopen/Materia-Server-Client-Assets/pull/39, closing.
