### ISSUE TITLE
Default collaboration level for new collaborators is 'nothing'.

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Materia#1158]
![screen shot 2018-09-17 at 10 22 45 am](https://user-images.githubusercontent.com/1275983/45629167-bff78b00-ba63-11e8-954a-342a0944a94e.png)

This is technically valid, but it seems nonsensical. Should probably default to 'View Scores'.

**Comment by clpetersonucf** [comment]
Resolved via #1231
