### ISSUE TITLE
Allow widgets creators to be restricted.

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Materia#1198]
There is potential to create widgets that we would only want to be created by users with the `basic_author` role.

This would most likely be something defined in the `install.yaml` for a widget and adjustable later on through the admin panel. Widgets restricted thus shouldn't appear in the catalog for users who lack the appropriate role.

**Comment by FrenjaminBanklin** [comment]
Also worth considering whether it should be possible for a person with the `basic_author` role to create one of these widgets and then share it with somebody who lacks the `basic_author` role - first assumption is that users without the role shouldn't be viable to share access to the widget with, but it's possible that at some point somebody might want to do that.

**Comment by iturgeon** [comment]
Merged into Ifrit. Should ship soon, closing.
