### ISSUE TITLE
Widget instance locking needs to occur when the creator is opened.

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Materia#1202]
Currently a widget instance is locked as soon as somebody clicks the 'Edit' button in the My Widgets page.

Not only does this mean that if somebody can't actually edit a widget (i.e. #1198) it'll still lock the widget, but it also means that going straight to the create url for a widget bypasses the lock check entirely.

Potentially the creator could have a new API call 'start_edit_session' or something which locks the widget, gets publish privileges, etc. all in one go.

**Comment by FrenjaminBanklin** [comment]
This should probably build on #1199.

**Comment by iturgeon** [comment]
Merged into Ifrit. Should ship soon, closing.
