### ISSUE TITLE
Move the currently logged in user display to the right hand side of the page

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia#1214]
The avatar and links for the current user should be moved to the right hand side.

Be sure to handle the responsive changes required for smaller displays.

![Screen Shot 2019-05-02 at 4 25 17 PM](https://user-images.githubusercontent.com/73480/57104651-e8807c80-6cf6-11e9-81f3-1736973b2227.png)

**Comment by clpetersonucf** [comment]
Completed via #1245
