### ISSUE TITLE
Inline help on my widgets to inform users of integration options

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia#1216]
There are instructors that are still exporting scores and importing them into Canvas.  This led me to the thought that we should try to make sure these people are aware of their options (they may have been using materia before it was able to sync)

Right now we can see 2 places where this would be useful as just in time help - Near the link on the mywidgets page, and on the score exporting dialog.

**Comment by iturgeon** [comment]
> Gonna just make sure the documentation is up to date and link out to that?
via @FrenjaminBanklin 

I'm thinking that as a minimum.  Though I could value in at least naming the options inline in case new options become available. Iif it's just a link, new options wouldn't get any attention.

**Comment by clpetersonucf** [comment]
Davis implemented half of this, but I still think it's important to include a better explainer on the "Share with your Students" section as well - likely bundled with a more comprehensive redo of the My Widgets page.
