### ISSUE TITLE
For non-scoring widgets, send a 100% participation scores

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia#1217]
In order to support use of non-scoring widgets for participation scoring - we could just send back scores when the widget is launched.

When a widget is lti launched and provides a score passback url  check to see if the widget is a non-scoring widget.  If it is, immediately send back a 100.  If not, let the widget's logic do what it does.

Add a dialog when using the picker to inform the user that they have chosen a non-scoring widget, and what it will do.

**Comment by clpetersonucf** [comment]
Implemented via #1226, individual widgets must implement the new engine call.
