### ISSUE TITLE
IDEA: create a role that can't author widgets

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia#1218]
**Problem**: Instructor clicks on View as Student in Canvas and launches into Materia.  The instructor is now the Test Student.

If the instructor then visits Materia and starts to create widgets (they can if students can create widgets!). 

Those widgets would now be owned by Test Student, not the instructor.  Those widgets would also be owned by any other instructor using the student view in their own courses.

**Solution?** Add a new role that would be used for Test Student that won't allow the user to create any widgets.

**Comment by clpetersonucf** [comment]
Implemented via #1272, though now we have to actually add some code to check for test users and grant the appropriate role.
