### ISSUE TITLE
My Widgets Overhaul

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1258]
We've completed an update to the catalog, now it's time for My Widgets. This ties in to a number of complimentary updates for this release: #1201, #1223, #1216, and potentially others.

**Comment by FrenjaminBanklin** [comment]
While we're in there, the code needs to be reformatted for readability. If possible, giving each tag's properties their own lines so we don't have to scroll horizontally to see what half of them are doing.

**Comment by clpetersonucf** [comment]
Closing, #1201 is still a valid issue but the remainder has been addressed.
