### ISSUE TITLE
"Refresh list" on LTI Picker appears to be broken again

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1259]
I've heard from two instructors recently that the button doesn't work, and requires exiting and then revisiting the LTI picker to receive the updated list.

**Comment by Goff-Davis** [comment]
I've been messing around with it. The refresh button only works for me on the very first refresh of a new user.

**Comment by clpetersonucf** [comment]
Completed as part of the Materia v7.0.1 release.
