### ISSUE TITLE
Main install task errors if crypt.php doesn't exist

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia#1294]
This is a problem that's been affecting 3rd parties trying to manually install Materia.  The main install wizard that helps you set config options fails when in prompt mode and crypt.php doesn't exist.

This, apparently isn't a problem when the `--quiet` flag is used so we never noticed it in our normal dev setup, and our own production setup uses Ansible to create the config settings.

**Comment by clpetersonucf** [comment]
Resolved via #1295, deployed as part of v7.0.1
