### ISSUE TITLE
IDEA: Add ownership + 'how do I gain access to this' info on  LTI preview embed page 

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Materia#1305]
As Materia is used over time, instructors will inherit widgets created by other faculty or TA's over time embedded in their courses.  Increasingly, users are trying to figure out how to get access to those tools.

Initial thoughts are the preview launch page should tell you who has perms to the widget (ie who do I contact?).  Potentially add info about who to contact (support) to gain ownership of widgets that can't be accessed.  

Potentially this spins off another feature idea to allow people to request access / approve via email links?

**Comment by clpetersonucf** [comment]
Implemented via #1344 as part of dev/9.
