### ISSUE TITLE
Create a new elevated Support role and corresponding "admin-lite" panel for frequent tasks

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1307]
There are a lot of tasks that Webcourses Support often need to perform in Materia that require one of us to perform. Allowing Support personnel to have an elevated role in the system could allow them to perform some of these tasks without bringing us into the loop.

Some regular tasks they could perform:

- Lookup users and instances
- View a user's individual plays with a given widget instance, including score, duration, and context (LTI or not?)
- Copy a widget instance
- Add other users as collaborators for a given widget instance
- View deleted widget instances and undelete
- Modifying instance settings like Guest Mode, attempt limits, and access windows
- Grant additional attempts for a given user for a given instance (this table exists in the DB but there isn't a GUI for it)

**Comment by ljoks** [comment]
see https://github.com/iturgeon/Materia/pull/3

**Comment by clpetersonucf** [comment]
Implemented in the React branch, closing
