### ISSUE TITLE
Homepage Frontend Redesign

### ISSUE THREAD

**Issue by aileenpongnon** [ucfopen/Materia#1363]
Refresh design of Materia landing page

current UI:
<img width="272" alt="Screen Shot 2022-02-22 at 2 31 05 PM" src="https://user-images.githubusercontent.com/42126081/155205116-d988f9ee-14c9-4f07-a2d5-a8ba754efdd0.png">

intended UI: 
![image](https://user-images.githubusercontent.com/42126081/155204043-b48adcaa-8365-4bf3-8b0c-5c1b6ab3b25e.png)

**Comment by clpetersonucf** [comment]
Implemented via #1364 and included in the React branch
