### ISSUE TITLE
Login Screen + My Profile Redesign

### ISSUE THREAD

**Issue by aileenpongnon** [ucfopen/Materia#1370]
Refresh design of Materia login page and my profile page

current UI:

**login page**
<img width="1280" alt="materialogin" src="https://user-images.githubusercontent.com/42126081/163435613-cffebb06-99f4-4ee1-a107-6b4504ac2312.png">

**my profile page**
<img width="1280" alt="materiamyprofile" src="https://user-images.githubusercontent.com/42126081/163435614-56d4dc74-6d05-4997-a141-00c03042f1ea.png">

![image](https://user-images.githubusercontent.com/42126081/164070822-454b267e-6746-4d9d-ac07-73662345f742.png)

intended UI:

**login page**
<img width="850" alt="login screen" src="https://user-images.githubusercontent.com/42126081/164044578-969a913f-17c9-46a2-aa49-9de02208b998.png">

my profile page
![image](https://user-images.githubusercontent.com/42126081/164070728-60ec13bb-1e8f-4e00-a7ab-015ecb921cd6.png)

![image](https://user-images.githubusercontent.com/42126081/164070751-c47d9cc1-b66b-4091-ba94-83093223fb5f.png)

**Comment by clpetersonucf** [comment]
These have been bundled into the react branch. Closing as addressed.
