### ISSUE TITLE
[React Branch] Remove remaining instances of jQuery to simplify dependency management

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1410]
jQuery is only used in a few locations:

- The score summary distribution graph in My Widgets
- The student performance distribution graph in the score screen
- The question importer dialog
- The media importer dialog
- The qset history dialog

All of these should be able to have the jquery removed and replaced fairly easily. It'd be nice to either use a homegrown distribution graph component or a more modern off-the-shelf solution that can be turned into a component.

**Comment by emanuelGitCodes** [comment]
I already completed the bar graph in My Widgets.
Where is the student performance distribution graph generated?

**Comment by emanuelGitCodes** [comment]
Apart from the 

- The score summary
- The student performance distribution graph

I don't see any jQuery in any of the others components mentioned.

**Comment by emanuelGitCodes** [comment]
Created a pull request called **Multiple issues #1417 **

**Comment by clpetersonucf** [comment]
Completed.
