### ISSUE TITLE
[React Branch] Score screen attempt list is inverted

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1413]
If I've attempted an instance 5 times, the latest attempt (attempt 5) is at the 0th index (attempt 1). The reverse should be true.

**Comment by emanuelGitCodes** [comment]
If this is for displaying the individual scores,
I added functionality in one of my branches where the first score appears in index position 0 and the final attempt in the last position. 

Is this what you are referring to?

**Comment by emanuelGitCodes** [comment]
Created a pull request name **Multiple issues #1417 **

**Comment by clpetersonucf** [comment]
This appears resolved
