### ISSUE TITLE
[React Branch] QA Feedback Master Issue

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1462]
Figured it'd be easier to create a single issue for people to submit feedback based on testing Materia v10 on QA. I can stub out issues based on items people submit.

**Comment by clpetersonucf** [comment]
1. Widget request pagination is fairly slow in My Widgets, and makes it pretty clear 10 per request is far too few. That number could safely be bumped up considerably.
2. The `-cores` aren't loading properly, which is expected. NGINX dev was providing a redirect, but the easier thing is to probably scrap putting compiled assets in `public/dist` and just emit them straight into the `public` directory, to better match where those assets were located before.
3. We still have to fix the issue where collaborators are being displayed in duplicate due to a variable type change from the PHP 8.1 update.
4. Views that should be sourced from `Materia-Theme-UCF` are not rendering yet

**Comment by clpetersonucf** [comment]
1. The creator Save History dialog's cancel button is operable
2. The widget icon alignment in the detail page is skewed
<img width="473" alt="Screenshot 2023-03-28 at 12 10 42 PM" src="https://user-images.githubusercontent.com/1268547/228302507-fe22fe6c-f2e4-423c-8beb-6b59f3ed175a.png">

**Comment by clpetersonucf** [comment]
1. Embed code isn't generating correct width/height values for a given widget instance
2. Embedded widgets may not be initializing properly - this should be tested with live instances, and not just local dev instances embedded in a local html file.

**Comment by clpetersonucf** [comment]
New issues discovered in the apha4 build:
- If a widget hash is present in the URL, the widget will not be selected when the instance list is fully loaded
- Copying or deleting a widget reloads the widget list, but the filter to sort them by creation date does not appear to be operating on the list
- The 'or create a new widget' button appears to be below the viewport of the LTI picker window in Canvas:
<img width="738" alt="Screenshot 2023-04-20 at 1 51 14 PM" src="https://user-images.githubusercontent.com/1268547/233447935-b89f27bd-4b1d-417d-86e0-d53bfa6a2f15.png">

**Comment by cayb0rg** [comment]
* Searching by creation date/time doesn’t work in the admin/support pages
* (Missing feature) Cannot see the owner of a widget in admin/support pages (could have been omitted for privacy?)
* Help/Support contact details missing
* Widget navigation in My Widgets disappears on smaller screen widths (<980px):

<img width="755" alt="Screenshot 2023-05-03 at 7 53 16 AM" src="https://user-images.githubusercontent.com/46247315/235921767-9f5201df-aa6c-4c2b-bb2c-a58366c680c4.png">

**Comment by clpetersonucf** [comment]
- Guest scores are not populating under Student Activity if a widget has Guest Mode enabled
- The score screen's "play again" option doesn't display in some circumstances where it should (ex: an instance has attempt limits enabled, but the student has remaining attempts available to them)

**Comment by clpetersonucf** [comment]
Resolved @cayb0rg's feedback items:
> Searching by creation date/time doesn’t work in the admin/support pages
There wasn't a good way to implement this, so the language suggesting this as an option has been updated.
> (Missing feature) Cannot see the owner of a widget in admin/support pages (could have been omitted for privacy?)
Instance owners are now displayed in instance admin. Also added instance IDs and user IDs as URL hashes for each admin page, allowing direct navigation to a user or instance management if you know their ID.
> Help/Support contact details missing
This requires enabling an additional environment variable, which is disabled by default. However, some locations where support information should be displayed may not display the overridden support details yet.
> Widget navigation in My Widgets disappears on smaller screen widths (<980px):
The media query that causes this has been removed, pending a better implementation of responsiveness on the My Widgets page.

**Comment by clpetersonucf** [comment]
Style improvements:
- The formatting of the 500 error page has some issues
- The "Are you sure you want to edit this widget?" should be reevaluated for clarity and necessity, with some small styling adjustments required regardless

**Comment by cayb0rg** [comment]
Users with view access cannot remove themselves as a collaborator. Not sure if this is a bug or if the option to delete themselves should be removed entirely.

**Comment by clpetersonucf** [comment]
The score screen is making a call to `apiGetWidgetInstanceScores` when in the context of reviewing another user's score from My Widgets, which is a behavior not present on production. This causes the score screen to error out in some situations due to permission mismatches, such as when the user has View Scores access to the widget.

**Comment by clpetersonucf** [comment]
- Notifications that inform the user about shared widgets should correctly link to the widgets.
- Certain My Widgets' page behaviors are still breaking when copying or deleting instances. Copying a widget forces the instance list to reload, and the newly created instance is not selected. Similarly, deleting a widget forces the instance list to reload, but the widget list is not displayed in chronologically descending order.

**Comment by clpetersonucf** [comment]
The widget catalog does not appear to filter widgets by the `in_catalog` flag.

**Comment by dmols** [comment]
What I've noticed thus far: 

- Alignment is really off for the Galaxy Fold, and get-started content div doesn't extend all the way across the screen. Might be best to leave it as is though, since even the landing page for the Fold doesn't have correct display.
- Some widgets have grammatical errors: "Hiring Decision Making Mulitple" is one of them
- 'Mobile Friendly' widgets that are not mobile accessible (wrong screen sizing): DNA Sequencer, Dodgeball, Enigma, Flashcards, Last Chance Cadet, etc 
- MyWidgets also doesn't display correctly

**Comment by clpetersonucf** [comment]
@dmols some more specificity is useful here:
> Might be best to leave it as is though, since even the landing page for the Fold doesn't have correct display.
What model of Fold? The cover screen or interior screen? Knowing those it's at least possible to emulate the display size using dev tools to identify styling issues.

> MyWidgets also doesn't display correctly
How so?

**Comment by cayb0rg** [comment]
* When embedding a widget's iframe into a page, there are scrollbars (maybe due to the Materia footer). The user can just make the width and height attributes slightly larger, but this may not be obvious
* ``refetchInstances`` in ``select-item.jsx`` is not a function
* Legacy urls (``https://localhost/lti/assignment?widget=[id]``) do not load in LTI Assignment Launch, dunno if these are necessary or still work in some cases
* Finishing a widget (new or old) that counts for points causes the alert "Something went wrong... : Invalid play session : is fatal" to appear. It still saves the score in Materia, just not Webcourses. Didn't get the error with widgets that have 0 points.

**Comment by dmols** [comment]
@clpetersonucf , here are some extra details on my review!
> What model of Fold? The cover screen or interior screen? Knowing those it's at least possible to emulate the display size using dev tools to identify styling issues.
> This I'm not entirely sure about since I haven't been able to test every model, but I assume the screen size is the same for every model, since users online have mentioned having issues with any and all. Also the dev tools for Google Chrome only indicate one option for the 'Fold'. 
> > MyWidgets also doesn't display correctly
>  Apologies for not elaborating fully; the page displays but it's extremely zoomed in, despite what device it's displayed on, even the standard 'responsive' option. The full page does not fully show when using the dev tools, and minimizing the window down to a certain range (wish I knew how to grab the exact pixel width but inspecting seems to make the issue worse) cuts off the right edge of the content.

**Comment by clpetersonucf** [comment]
The footer can become visually decoupled from the widget player when the embedded iframe scales responsively (this was embedded as an assignment in Webcourses):
<img width="1090" alt="Screenshot 2023-08-15 at 2 31 47 PM" src="https://github.com/ucfopen/Materia/assets/1268547/a9b63728-7682-4a92-af81-779b31cf7d44">

**Comment by cayb0rg** [comment]
* Hash changes while on the My Widgets Page do not redirect to that widget (such as when you click on a link in a notification)
* Students with only the support_user role (no basic_author role) cannot be added as collaborators. It doesn't save, but it also doesn't raise any errors. POST /api/json/permissions_set returns 200. If this is intentional, we should show an error when the user attempts to save.
* Last name overlaps role in Collaborator:
 <img width="322" alt="image" src="https://github.com/ucfopen/Materia/assets/46247315/02e3b7fc-4bc1-474f-b6c6-81565e09e39c">

* Making a copy of a widget in Instance Admin sets the hash to an object

**Comment by clpetersonucf** [comment]
@cayb0rg just a heads up I have fixes for 1 and 4 in https://github.com/ucfopen/Materia/pull/1492

**Comment by clpetersonucf** [comment]
- The catalog is duplicating featured widgets, including them in the featured section and then again in the non-featured section.

**Comment by clpetersonucf** [comment]
- Widget previews do not provide a Preview Again button.
- Custom score screens often fail to render due to an error originating from `drawScoreCircle()`, which probably shouldn't be called in the first place when a custom score screen is being rendered
- Custom score screens are very slow to initially render

**Comment by clpetersonucf** [comment]
- Enigma widgets don't proceed past the "Submit for review" screen on QA when embedded as assignments in Webcourses. They do appear to be marked as complete, however.
- The "Previewing Prior Save" action bar overlay in the creator, activated when viewing an older qset from the Save History dialog, has style issues in Safari. The buttons overflow, rendering the Cancel button unclickable.

**Comment by clpetersonucf** [comment]
- Score screen overviews are still not updating properly when selecting a different previous attempt (I swear to god I fixed this)

**Comment by clpetersonucf** [comment]
- Viewing single scores is not conditionally disabling the header when `IS_EMBEDDED` is provided as a window value
- The score screen still enters a failure state when viewing single scores for widgets (for example, in the Canvas speed grader) that the current user does not have access to
