### ISSUE TITLE
[React Branch] Deleting current user in Collaboration Dialog

### ISSUE THREAD

**Issue by cayb0rg** [ucfopen/Materia#1470]
Deleting the current user in the collaboration dialog does not refresh the My Widgets Page to reflect the new permissions.

**Comment by clpetersonucf** [comment]
I attempted to resolve this in 0b0ca69a56a4c281214c30295515421cd6871c8e which is now part of #1468

**Comment by clpetersonucf** [comment]
Resolved :+1:
