### ISSUE TITLE
Client side needs enforcement of instance title length

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#1598]
Right now an instance title that's too lengthy returns a 403 error from `widget_instance_save`, triggering a failure state in the creator

**Comment by chrissolanilla** [comment]
I have made changes to my fork with branch 1600/save-draft-button and opened a PR

**Comment by clpetersonucf** [comment]
Addressed via #1604

**Comment by clpetersonucf** [comment]
Closing, now on prod.
