### ISSUE TITLE
Student Activity: Empty search results display error (Safari)

### ISSUE THREAD

**Issue by dgwn** [ucfopen/Materia#1619]
In Safari in the My Widgets Panel > Published Widget > Individual Scores, there appears to be a styling bug with the score list table being visible when there are no results.

<img width="325" alt="Screenshot 2024-11-12 at 1 14 14 PM" src="https://github.com/user-attachments/assets/e28d418e-964c-4c65-bb9c-e337cedfcfe4">

---------

SafarI:
<img width="804" alt="Screenshot 2024-11-12 at 10 51 38 AM" src="https://github.com/user-attachments/assets/6795515c-f3f4-45e2-a038-0bb796905bf1">

Firefox:
<img width="751" alt="Screenshot 2024-11-12 at 10 51 21 AM" src="https://github.com/user-attachments/assets/e9ba1688-5f0c-4bf2-815e-b53cef73fa55">

**Comment by clpetersonucf** [comment]
Addressed via #1623 and now on prod, closing :+1:
