### ISSUE TITLE
Copying widgets via the widget:copy task includes the permissions of the original widget

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Materia#394]
The primary use case for this task is to investigate issues with instances. The current behavior causes a problem since you ideally don't want the original owner of the initial instance to know about the copy that took place.

**Comment by iturgeon** [comment]
Update, we ran into this again today.

Ownership when copying a widget needs to be reviewed and cleaned up. This probably needs a flow chart and to take into account:

1. The user copying it isn't necessarily the original creator
2. should the new instance be owned by the person creating the copy
3. should the people who had access to the old widget get permissions to the new one?
4. We should add a Session_Activity for `DUPLICATE_WIDGET_INSTANCE` 
5. notifying the user about what happens to the above things (remove assumptions for them)
