### ISSUE TITLE
Remove session_play_create from API

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Materia#647]
Nothing client-side is calling this, so this probably shouldn't be an API method. Need to determine where to put the code that session_play_create is running (perhaps move into Session_Play::start).

**Comment by iturgeon** [comment]
It's used now on the widget details page - https://github.com/ucfopen/Materia-Server-Client-Assets/blob/1dcf147eab325285cd3055cd1d574b86831a1a47/src/js/controllers/ctrl-widget-details.js#L157

Also - I think if we ever want to start using a pure api approach (ie a mobile app), we'll need to use this
