### ISSUE TITLE
Catalog Overhaul: Phase II

### ISSUE THREAD

**Issue by clpetersonucf** [ucfopen/Materia#857]
We've been wanting to revisit the Catalog page for a while. I'll also be consolidating some wishlist items from old commits:

**Design overhaul:** more flexibility, improved responsive design, better organization. Also, those Infocards wreak all sorts of havoc with front-end testing, like Selenium.

**Filters, sorting:** based on an old issue, we've had some ideas:

```
Sorting presets are currently limited to title and creation date. Additional sorting criteria should be created at some point based on metadata, i.e., category type, community, stock widgets vs. custom widgets, etc. This will probably require adjustments to the UI as well.
```

**Better search parameters, communities:** The idea of widget "communities" was previously suggested as well, but its implementation hasn't really been fleshed out.

**Better widget detail page:** I'd also like to see the detail page overhauled, in lockstep with the design language we end up using for the Catalog. We've also talked about including citations or research that promotes the instructional design advantages to using a particular widget.

**Comment by iturgeon** [comment]
I'm going to mark this completed as it's merged into ifrit dev branch now 👍
