### ISSUE TITLE
Add Fake S3 Container to Materia Docker

### ISSUE THREAD

**Issue by samuel-belcastro** [ucfopen/Materia#876]
Fake S3 will allow Materia Docker to emulate a real Amazon S3 server which will be required for the new upload process outlined in [Materia Issue #894](https://github.com/ucfcdl/Materia/issues/894).

This container will also house the python script used to resize the uploaded images on Amazon Lamba. Once an image is sent to this container, a watch file will find the new file, create a thumbnail, and store that thumbnail in a new bucket.

**Comment by iturgeon** [comment]
Some version of this was implemented
