### ISSUE TITLE
jQuery dependence should be stripped out of Materia.

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Materia#917]
There are currently areas of the Materia core JS code that rely on jQuery being loaded within the page they're running on, such as Materia.Coms.Json, Materia.Engine, Materia.CreatorCore, and so on.

Reliance on jQuery in these libraries should be stripped out wherever possible and have replaced with their standard JS equivalents.

**Comment by iturgeon** [comment]
I believe jquery has been reduced as much as it can while we still rely on jqPlot and datatables
