### ISSUE TITLE
Deleting a widget instance completely removes any LTI associations.

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Materia#963]
Currently when a widget instance is deleted, the data pertaining to that instance is kept around but any LTI associations it has are removed permanently. This shouldn't be a significant problem as another LTI association should be built automatically if that embedded widget is visited, but we still lose any historical information.

Suggestion: Have them act the same; give LTI associations a 'is_deleted' column or something similar, toggle it as necessary when deleting/restoring relevant widget instances.

**Comment by iturgeon** [comment]
Maaybe not a big deal since the lti launch data of each play is kept now
